version: "3"
services:
  es:
    image: elasticsearch:8.3.2
    container_name: es
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
      - ./volumes/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./volumes/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      discovery.type: single-node
      TZ: Asia/Shanghai
    restart: always
  kibana:
    image: kibana:8.3.2
    container_name: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/kibana/data:/usr/share/kibana/data
      - ./volumes/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - es
    restart: always
  mysql:
    image: mysql:8
    container_name: mysql
    networks:
      - elastic
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/tb_hotel.sql:/tb_hotel.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: es
      TZ: Asia/Shanghai
    restart: always
  ampq:
    image: rabbitmq:3-management
    container_name: ampq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - elastic
    volumes:
      - ./volumes/ampq/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: elastic
      RABBITMQ_DEFAULT_PASS: yq7UbfMeNNGkvFh2gBf_
      RABBITMQ_DEFAULT_VHOST: /
      TZ: Asia/Shanghai
    restart: always
networks:
  elastic: