logging:
  level:
    web: DEBUG
    com.windcf.eslearn: DEBUG
    # 打印query dsl
    org.springframework.data.elasticsearch: TRACE
    sql: DEBUG
#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
springdoc:
  swagger-ui:
    enabled: true
    path: /docs
  packages-to-scan: com.windcf.eslearn.controller